###########################################################
#                                                         #
#                       MAKEFILE                          #
#                                                         #
###########################################################
CC = gcc
CXX = gcc

.PHONY: clean

clean:
	-rm -f *.ind
	-rm -f *.blg
	-rm -f *.dvi
	-rm -f *.idx
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.bbl
	-rm -f *.ilg
	-rm -f *.gz
	-rm -f *.toc
	-rm -f *.out
	-rm -f *.lof
	-rm -f *.md
	-rm -f *.pdf
